import 'contact.dart';

class ContactsData {
  static const List<Contact> contacts = [
    Contact(
      name: 'John Smith',
      phone: '+91 123456789',
      designation: 'Software Developer',
      imageUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
      aboutMe: 'Passionate about building mobile apps with Flutter and Dart.',
      email: 'john.smith@example.com',
    ),
    Contact(
      name: 'Sarah Johnson',
      phone: '+91 123456790',
      designation: 'UI/UX Designer',
      imageUrl: 'https://randomuser.me/api/portraits/women/2.jpg',
      aboutMe: 'Loves creating intuitive and visually appealing designs.',
      email: 'sarah.johnson@example.com',
    ),
    Contact(
      name: 'Michael Brown',
      phone: '+91 123456791',
      designation: 'Backend Developer',
      imageUrl: 'https://randomuser.me/api/portraits/men/3.jpg',
      aboutMe: 'Experienced in building scalable APIs with Node.js.',
      email: 'michael.brown@example.com',
    ),
    Contact(
      name: 'Emily Davis',
      phone: '+91 123456792',
      designation: 'Frontend Developer',
      imageUrl: 'https://randomuser.me/api/portraits/women/4.jpg',
      aboutMe: 'Skilled in crafting responsive web apps with React.',
      email: 'emily.davis@example.com',
    ),
    Contact(
      name: 'David Wilson',
      phone: '+91 123456793',
      designation: 'Mobile Developer',
      imageUrl: 'https://randomuser.me/api/portraits/men/5.jpg',
      aboutMe: 'Focused on creating seamless iOS apps with Swift.',
      email: 'david.wilson@example.com',
    ),
    Contact(
      name: 'Laura Martinez',
      phone: '+91 123456794',
      designation: 'Data Scientist',
      imageUrl: 'https://randomuser.me/api/portraits/women/6.jpg',
      aboutMe: 'Enjoys analyzing data to uncover insights using Python.',
      email: 'laura.martinez@example.com',
    ),
    Contact(
      name: 'James Taylor',
      phone: '+91 123456795',
      designation: 'DevOps Engineer',
      imageUrl: 'https://randomuser.me/api/portraits/men/7.jpg',
      aboutMe: 'Specializes in automating deployments with CI/CD tools.',
      email: 'james.taylor@example.com',
    ),
    Contact(
      name: 'Sophia Anderson',
      phone: '+91 123456796',
      designation: 'Graphic Designer',
      imageUrl: 'https://randomuser.me/api/portraits/women/8.jpg',
      aboutMe: 'Passionate about branding and visual storytelling.',
      email: 'sophia.anderson@example.com',
    ),
    Contact(
      name: 'Robert Lee',
      phone: '+91 123456797',
      designation: 'Cybersecurity Expert',
      imageUrl: 'https://randomuser.me/api/portraits/men/9.jpg',
      aboutMe: 'Dedicated to securing systems through rigorous testing.',
      email: 'robert.lee@example.com',
    ),
    Contact(
      name: 'Olivia Clark',
      phone: '+91 123456798',
      designation: 'Product Manager',
      imageUrl: 'https://randomuser.me/api/portraits/women/10.jpg',
      aboutMe: 'Experienced in leading tech teams to deliver products.',
      email: 'olivia.clark@example.com',
    ),
    Contact(
      name: 'William Harris',
      phone: '+91 123456799',
      designation: 'Full-Stack Developer',
      imageUrl: 'https://randomuser.me/api/portraits/men/11.jpg',
      aboutMe: 'Proficient in building end-to-end solutions with Django.',
      email: 'william.harris@example.com',
    ),
    Contact(
      name: 'Ava Lewis',
      phone: '+91 123456800',
      designation: 'Content Strategist',
      imageUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
      aboutMe: 'Focused on creating impactful digital marketing content.',
      email: 'ava.lewis@example.com',
    ),
    Contact(
      name: 'Thomas Walker',
      phone: '+91 123456801',
      designation: 'Database Administrator',
      imageUrl: 'https://randomuser.me/api/portraits/men/13.jpg',
      aboutMe: 'Skilled in optimizing databases for performance.',
      email: 'thomas.walker@example.com',
    ),
    Contact(
      name: 'Mia Robinson',
      phone: '+91 123456802',
      designation: 'Machine Learning Engineer',
      imageUrl: 'https://randomuser.me/api/portraits/women/14.jpg',
      aboutMe: 'Interested in advancing AI with natural language processing.',
      email: 'mia.robinson@example.com',
    ),
    Contact(
      name: 'Charles Hall',
      phone: '+91 123456803',
      designation: 'Cloud Architect',
      imageUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
      aboutMe: 'Experienced in designing scalable cloud solutions.',
      email: 'charles.hall@example.com',
    ),
    Contact(
      name: 'Isabella Allen',
      phone: '+91 123456804',
      designation: 'Game Developer',
      imageUrl: 'https://randomuser.me/api/portraits/women/16.jpg',
      aboutMe: 'Passionate about creating immersive games with Unity.',
      email: 'isabella.allen@example.com',
    ),
    Contact(
      name: 'Daniel Young',
      phone: '+91 123456805',
      designation: 'Blockchain Developer',
      imageUrl: 'https://randomuser.me/api/portraits/men/17.jpg',
      aboutMe: 'Focused on building decentralized apps with Ethereum.',
      email: 'daniel.young@example.com',
    ),
    Contact(
      name: 'Grace King',
      phone: '+91 123456806',
      designation: 'Technical Writer',
      imageUrl: 'https://randomuser.me/api/portraits/women/18.jpg',
      aboutMe: 'Specializes in creating clear API documentation.',
      email: 'grace.king@example.com',
    ),
    Contact(
      name: 'Joseph Wright',
      phone: '+91 123456807',
      designation: 'Embedded Systems Engineer',
      imageUrl: 'https://randomuser.me/api/portraits/men/19.jpg',
      aboutMe: 'Enjoys working on IoT projects with microcontrollers.',
      email: 'joseph.wright@example.com',
    ),
    Contact(
      name: 'Chloe Scott',
      phone: '+91 123456808',
      designation: 'QA Engineer',
      imageUrl: 'https://randomuser.me/api/portraits/women/20.jpg',
      aboutMe: 'Dedicated to ensuring quality through automated testing.',
      email: 'chloe.scott@example.com',
    ),
  ];
}